In [2]:
import pandas as pd
s1=pd.Series([12,45,68,54,33,78,88,91])
s1

0    12
1    45
2    68
3    54
4    33
5    78
6    88
7    91
dtype: int64

In [5]:
s2=pd.Series([12,45,68,54,33,78,88,91], index=["a","b","c","d","e","f","g","h"])
s2

a    12
b    45
c    68
d    54
e    33
f    78
g    88
h    91
dtype: int64

In [11]:
print(s1[1])
print(s2["a"])

45
12

In [12]:
data = {
    "name": ["Alice", "Bob", "Charlie"],
    "age": [25, 30, 35],
    "city": ["Delhi", "Mumbai", "Bangalore"]
}

df = pd.DataFrame(data)   #Creating DataFrame with dictionary of lists.
print(df)

      name  age       city
0    Alice   25      Delhi
1      Bob   30     Mumbai
2  Charlie   35  Bangalore

In [13]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [14]:
df.columns

Index(['name', 'age', 'city'], dtype='object')

In [15]:
df.index=[1,2,3]

In [16]:
df

      name  age       city
1    Alice   25      Delhi
2      Bob   30     Mumbai
3  Charlie   35  Bangalore

In [17]:
df.columns=["Name","Age","City"]

In [18]:
df

      Name  Age       City
1    Alice   25      Delhi
2      Bob   30     Mumbai
3  Charlie   35  Bangalore