# Creating DataFrame

In [1]:
import pandas as pd

## From list of lists

In [2]:
data=[["Harry", 89],["Carry", 79],["Rohan", 67]]
data

[['Harry', 89], ['Carry', 79], ['Rohan', 67]]

In [3]:
df=pd.DataFrame(data,columns=["Name","Marks"])
df

    Name  Marks
0  Harry     89
1  Carry     79
2  Rohan     67

## From Dictionary of Lists

In [4]:
# Creating DataFrame Using 
data={"Name":["Atul","Bheem", "Kalia", "John"],
     "Marks":[24, 67, 54, 90]
     }
data

{'Name': ['Atul', 'Bheem', 'Kalia', 'John'], 'Marks': [24, 67, 54, 90]}

In [5]:
df=pd.DataFrame(data)
df

    Name  Marks
0   Atul     24
1  Bheem     67
2  Kalia     54
3   John     90

## From NumPy Arrays

In [6]:
# Creating DataFrame Using NumPy Arrays
import numpy as np
arr= np.array([[12,34,56],[57,47,98]])
arr

array([[12, 34, 56],
       [57, 47, 98]])

In [7]:
df=pd.DataFrame(arr, columns=["a","b","c"])
df

    a   b   c
0  12  34  56
1  57  47  98

## From Excel Files

In [8]:
df=pd.read_excel("data1.xlsx")
df

       Name School  Marks
0    Subham    ITK     34
1    Joshua     DD     56
2     Rishi    UPS     78
3     Akash    WPS     33
4     Manav    NTK     29
5     Mohit    BBB     44
6     Arpit    UTK     76
7  Abhishek    CLC     88

# Creating DataFrame From CSV Files

In [10]:
df=pd.read_csv("data1.csv")
df

       Name School  Marks
0    Subham    ITK     34
1    Joshua     DD     56
2     Rishi    UPS     78
3     Akash    WPS     33
4     Manav    NTK     29
5     Mohit    BBB     44
6     Arpit    UTK     76
7  Abhishek    CLC     88

# Creating DataFrame From json Files

In [12]:
df=pd.read_json("data1.json")
df

    name    lang
0  Harry  Python
1  Rohan       C