# Creating DataFrame

In [5]:
import pandas as pd

## From list of lists

In [6]:
data=[["Harry", 89],["Carry", 79],["Rohan", 67]]
data

[['Harry', 89], ['Carry', 79], ['Rohan', 67]]

In [7]:
df=pd.DataFrame(data,columns=["Name","Marks"])
df

    Name  Marks
0  Harry     89
1  Carry     79
2  Rohan     67

## From Dictionary of Lists

In [8]:
# Creating DataFrame Using 
data={"Name":["Atul","Bheem", "Kalia", "John"],
     "Marks":[24, 67, 54, 90]
     }
data

{'Name': ['Atul', 'Bheem', 'Kalia', 'John'], 'Marks': [24, 67, 54, 90]}

In [9]:
df=pd.DataFrame(data)
df

    Name  Marks
0   Atul     24
1  Bheem     67
2  Kalia     54
3   John     90

## From NumPy Arrays

In [10]:
# Creating DataFrame Using NumPy Arrays
import numpy as np
arr= np.array([[12,34,56],[57,47,98]])
arr

array([[12, 34, 56],
       [57, 47, 98]])

In [11]:
df=pd.DataFrame(arr, columns=["a","b","c"])
df

    a   b   c
0  12  34  56
1  57  47  98

## From Excel Files

In [12]:
df=pd.read_excel("data1.xlsx")
df

       Name School  Marks
0    Subham    ITK     34
1    Joshua     DD     56
2     Rishi    UPS     78
3     Akash    WPS     33
4     Manav    NTK     29
5     Mohit    BBB     44
6     Arpit    UTK     76
7  Abhishek    CLC     88

# Creating DataFrame From CSV Files

In [13]:
df=pd.read_csv("data1.csv")
df

       Name School  Marks
0    Subham    ITK     34
1    Joshua     DD     56
2     Rishi    UPS     78
3     Akash    WPS     33
4     Manav    NTK     29
5     Mohit    BBB     44
6     Arpit    UTK     76
7  Abhishek    CLC     88

# Creating DataFrame From json Files

In [14]:
df=pd.read_json("data1.json")
df

    name    lang
0  Harry  Python
1  Rohan       C

## From the Web (Example: CSV from URL)

In [15]:
df=pd.read_csv("https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv")
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

## EDA(Exploratory Data Analysis)
* df.head()           - First 5 rows
* df.tail()           - Last 5 rows
* df.info()           - Column info: types, non-nulls
* df.describe()       - Stats for numeric columns
* df.columns          - List of column names
* df.shape            - (rows, columns)

In [17]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [18]:
df.tail()

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [20]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [24]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [25]:
df.shape

(150, 5)