In [2]:
import pandas as pd

df=pd.read_csv("actorfilms.csv")
df

,Actor,ActorID,Film,Year,Votes,Rating,FilmID
0,Fred Astaire,nm0000001,Ghost Story,1981,7731,6.3,tt0082449
1,Fred Astaire,nm0000001,The Purple Taxi,1977,533,6.6,tt0076851
2,Fred Astaire,nm0000001,The Amazing Dobermans,1976,369,5.3,tt0074130
3,Fred Astaire,nm0000001,The Towering Inferno,1974,39888,7.0,tt0072308
4,Fred Astaire,nm0000001,Midas Run,1969,123,4.8,tt0064664
...,...,...,...,...,...,...,...
191868,Roman Griffin Davis,nm9877392,Jojo Rabbit,2019,310904,7.9,tt2584384
191869,Lexi Rabe,nm9962642,Silk Road,2021,2050,5.9,tt7937254
191870,Lexi Rabe,nm9962642,Avengers: Endgame,2019,849079,8.4,tt4154796
191871,Lexi Rabe,nm9962642,Godzilla: King of the Monsters,2019,146737,6.0,tt3741700
191872,Inde Navarrette,nm9984699,Wander Darkly,2020,776,5.8,tt8902978

In [3]:
df["Actor"] #Single column as Series

0                Fred Astaire
1                Fred Astaire
2                Fred Astaire
3                Fred Astaire
4                Fred Astaire
                 ...
191868    Roman Griffin Davis
191869              Lexi Rabe
191870              Lexi Rabe
191871              Lexi Rabe
191872        Inde Navarrette
Name: Actor, Length: 191873, dtype: object

In [5]:
df[["Actor","Film"]] #Multiple columns as DataFrame

                      Actor                            Film
0              Fred Astaire                     Ghost Story
1              Fred Astaire                 The Purple Taxi
2              Fred Astaire           The Amazing Dobermans
3              Fred Astaire            The Towering Inferno
4              Fred Astaire                       Midas Run
...                     ...                             ...
191868  Roman Griffin Davis                     Jojo Rabbit
191869            Lexi Rabe                       Silk Road
191870            Lexi Rabe               Avengers: Endgame
191871            Lexi Rabe  Godzilla: King of the Monsters
191872      Inde Navarrette                   Wander Darkly

[191873 rows x 2 columns]

In [17]:
df.loc[0]  # First row (by label)

Actor      Fred Astaire
ActorID       nm0000001
Film        Ghost Story
Year               1981
Votes              7731
Rating              6.3
FilmID        tt0082449
Name: 0, dtype: object

In [18]:
df.iloc[0] # First row (by position)

Actor      Fred Astaire
ActorID       nm0000001
Film        Ghost Story
Year               1981
Votes              7731
Rating              6.3
FilmID        tt0082449
Name: 0, dtype: object

In [19]:
df.loc[0, "Actor"]        # Value at row 0, column 'Actor'

'Fred Astaire'

In [22]:
df.iloc[0, 2]            # Value at row 0, column at index 2

'Ghost Story'

In [33]:
df.loc[35:40, ["Actor", "Film", "Rating"]] # Rows 35 to 40, selected columns

            Actor                Film  Rating
35   Fred Astaire             Roberta     7.1
36   Fred Astaire    The Gay Divorcee     7.5
37   Fred Astaire  Flying Down to Rio     6.6
38   Fred Astaire        Dancing Lady     6.8
39  Lauren Bacall  Ernest & Celestine     7.9
40  Lauren Bacall          The Forger     5.4

In [34]:
df.iloc[35:40, [0,2,5]] # Rows and cols by index position

            Actor                Film  Rating
35   Fred Astaire             Roberta     7.1
36   Fred Astaire    The Gay Divorcee     7.5
37   Fred Astaire  Flying Down to Rio     6.6
38   Fred Astaire        Dancing Lady     6.8
39  Lauren Bacall  Ernest & Celestine     7.9

In [36]:
df.at[0, "Actor"]       # Fast label-based access

'Fred Astaire'

In [40]:
df.iat[0, 2]           # Fast position-based access

'Ghost Story'

In [43]:
df.columns

Index(['Actor', 'ActorID', 'Film', 'Year', 'Votes', 'Rating', 'FilmID'], dtype='object')

In [45]:
df[df["Rating"]>9]

,Actor,ActorID,Film,Year,Votes,Rating,FilmID
275,Marlon Brando,nm0000008,The Godfather,1972,1642278,9.2,tt0068646
6285,Morgan Freeman,nm0000151,The Shawshank Redemption,1994,2371548,9.3,tt0111161
8570,Al Pacino,nm0000199,The Godfather,1972,1642278,9.2,tt0068646
9017,Tim Robbins,nm0000209,The Shawshank Redemption,1994,2371548,9.3,tt0111161
13189,Clancy Brown,nm0000317,The Shawshank Redemption,1994,2371548,9.3,tt0111161
15964,Robert Duvall,nm0000380,The Godfather,1972,1642278,9.2,tt0068646
19780,Diane Keaton,nm0000473,The Godfather,1972,1642278,9.2,tt0068646
35105,James Caan,nm0001001,The Godfather,1972,1642278,9.2,tt0068646
36164,John Cazale,nm0001030,The Godfather,1972,1642278,9.2,tt0068646
37097,Sofia Coppola,nm0001068,The Godfather,1972,1642278,9.2,tt0068646
44383,Sterling Hayden,nm0001330,The Godfather,1972,1642278,9.2,tt0068646
47917,Nathan Lane,nm0001447,National Theatre Live: Angels in America Part ...,2017,378,9.1,tt6847810
55729,Mark Rolston,nm0001679,The Shawshank Redemption,1994,2371548,9.3,tt0111161
57710,Talia Shire,nm0001735,The Godfather,1972,1642278,9.2,tt0068646
60744,Abe Vigoda,nm0001820,The Godfather,1972,1642278,9.2,tt0068646
63643,Richard Conte,nm0002017,The Godfather,1972,1642278,9.2,tt0068646
67668,Gil Bellows,nm0004743,The Shawshank Redemption,1994,2371548,9.3,tt0111161
72158,Paul McCrane,nm0005204,The Shawshank Redemption,1994,2371548,9.3,tt0111161
76468,William Sadler,nm0006669,The Shawshank Redemption,1994,2371548,9.3,tt0111161
84749,Richard Bright,nm0109175,The Godfather,1972,1642278,9.2,tt0068646
87572,Richard S. Castellano,nm0144710,The Godfather,1972,1642278,9.2,tt0068646
94294,Jeffrey DeMunn,nm0218810,The Shawshank Redemption,1994,2371548,9.3,tt0111161
103140,Adam Godley,nm0324134,The Lehman Trilogy,2019,164,9.2,tt10127546
104671,Julie Gregg,nm0339589,The Godfather,1972,1642278,9.2,tt0068646
105588,Bob Gunton,nm0348409,The Shawshank Redemption,1994,2371548,9.3,tt0111161
115408,Morgana King,nm0455088,The Godfather,1972,1642278,9.2,tt0068646
118927,Al Lettieri,nm0504803,The Godfather,1972,1642278,9.2,tt0068646
119904,Tony Lip,nm0513401,The Godfather,1972,1642278,9.2,tt0068646
125785,Don McManus,nm0573134,The Shawshank Redemption,1994,2371548,9.3,tt0111161
127021,Ben Miles,nm0587060,The Lehman Trilogy,2019,164,9.2,tt10127546
127976,Lenny Montana,nm0598926,The Godfather,1972,1642278,9.2,tt0068646
136817,David Proval,nm0698998,The Shawshank Redemption,1994,2371548,9.3,tt0111161
140095,Alex Rocco,nm0733678,The Godfather,1972,1642278,9.2,tt0068646
141951,Gianni Russo,nm0751625,The Godfather,1972,1642278,9.2,tt0068646
144240,Vito Scotti,nm0780005,The Godfather,1972,1642278,9.2,tt0068646
146258,Frank Sivero,nm0803370,The Godfather,1972,1642278,9.2,tt0068646
147766,Joe Spinell,nm0818874,The Godfather,1972,1642278,9.2,tt0068646
148268,Simonetta Stefanelli,nm0824940,The Godfather,1972,1642278,9.2,tt0068646
152087,Russell Tovey,nm0869871,National Theatre Live: Angels in America Part ...,2017,378,9.1,tt6847810
157439,James Whitmore,nm0926235,The Shawshank Redemption,1994,2371548,9.3,tt0111161
174382,Denise Gough,nm1740112,National Theatre Live: Angels in America Part ...,2017,378,9.1,tt6847810
176609,Andrew Garfield,nm1940449,National Theatre Live: Angels in America Part ...,2017,378,9.1,tt6847810
182814,Nathan Stewart-Jarrett,nm2805533,National Theatre Live: Angels in America Part ...,2017,378,9.1,tt6847810
187973,Harry Styles,nm4089170,Behind the Album: The Performances,2017,199,9.1,tt7318364
189079,James McArdle,nm4574630,National Theatre Live: Angels in America Part ...,2017,378,9.1,tt6847810

In [46]:
df.at[182814, "Film"]

'National Theatre Live: Angels in America Part Two - Perestroika'

In [51]:
df[df["Rating"]>9]["Actor"]

275                Marlon Brando
6285              Morgan Freeman
8570                   Al Pacino
9017                 Tim Robbins
13189               Clancy Brown
15964              Robert Duvall
19780               Diane Keaton
35105                 James Caan
36164                John Cazale
37097              Sofia Coppola
44383            Sterling Hayden
47917                Nathan Lane
55729               Mark Rolston
57710                Talia Shire
60744                 Abe Vigoda
63643              Richard Conte
67668                Gil Bellows
72158               Paul McCrane
76468             William Sadler
84749             Richard Bright
87572      Richard S. Castellano
94294             Jeffrey DeMunn
103140               Adam Godley
104671               Julie Gregg
105588                Bob Gunton
115408              Morgana King
118927               Al Lettieri
119904                  Tony Lip
125785               Don McManus
127021                 Ben Miles
127976             Lenny Montana
136817              David Proval
140095                Alex Rocco
141951              Gianni Russo
144240               Vito Scotti
146258              Frank Sivero
147766               Joe Spinell
148268      Simonetta Stefanelli
152087             Russell Tovey
157439            James Whitmore
174382              Denise Gough
176609           Andrew Garfield
182814    Nathan Stewart-Jarrett
187973              Harry Styles
189079             James McArdle
Name: Actor, dtype: object

In [60]:
df[(df["Rating"]>7.5) & (df["Year"]>=2019)]

,Actor,ActorID,Film,Year,Votes,Rating,FilmID
3783,Brad Pitt,nm0000093,Once Upon a Time... In Hollywood,2019,569358,7.6,tt7131622
3882,Gillian Anderson,nm0000096,All About Eve,2019,315,8.2,tt9652730
3965,Patricia Arquette,nm0000099,Toy Story 4,2019,208751,7.8,tt1979376
5100,Kevin Costner,nm0000126,Zack Snyder's Justice League,2021,242474,8.2,tt12361974
5103,Kevin Costner,nm0000126,The Art of Racing in the Rain,2019,25750,7.6,tt1478839
...,...,...,...,...,...,...,...
191814,Camille Kostek,nm8814069,Free Guy,2021,446,7.6,tt6264654
191845,Megan Best,nm9412217,Nobody,2021,5764,7.7,tt7888964
191852,Jessie Mei Li,nm9438171,All About Eve,2019,315,8.2,tt9652730
191868,Roman Griffin Davis,nm9877392,Jojo Rabbit,2019,310904,7.9,tt2584384
191870,Lexi Rabe,nm9962642,Avengers: Endgame,2019,849079,8.4,tt4154796

In [58]:
df[(df["Rating"]>9) | (df["Year"]>2019)]

,Actor,ActorID,Film,Year,Votes,Rating,FilmID
275,Marlon Brando,nm0000008,The Godfather,1972,1642278,9.2,tt0068646
1856,Sophia Loren,nm0000047,The Life Ahead,2020,10059,6.8,tt10627584
3675,Gong Li,nm0000084,Mulan,2020,116927,5.6,tt4566758
3676,Gong Li,nm0000084,Leap,2020,802,6.7,tt10670442
3708,John Cleese,nm0000092,The Very Excellent Mr. Dundee,2020,1091,4.9,tt8560172
...,...,...,...,...,...,...,...
191858,Nico Hiraga,nm9569934,Moxie,2021,14412,6.7,tt6432466
191861,Sadie Stanley,nm9642493,The Sleepover,2020,8243,5.6,tt10888708
191863,Julia Fox,nm9681752,PVT CHAT,2020,409,5.5,tt8110004
191869,Lexi Rabe,nm9962642,Silk Road,2021,2050,5.9,tt7937254
191872,Inde Navarrette,nm9984699,Wander Darkly,2020,776,5.8,tt8902978

In [63]:
df.query("Year > 1995 and Rating == 8.5") #Query by default returns a copy

,Actor,ActorID,Film,Year,Votes,Rating,FilmID
4169,Fairuza Balk,nm0000103,American History X,1998,1043588,8.5,tt0120586
5194,Russell Crowe,nm0000128,Gladiator,2000,1355908,8.5,tt0172495
5631,Leonardo DiCaprio,nm0000138,The Departed,2006,1203732,8.5,tt0407887
8396,Jack Nicholson,nm0000197,The Departed,2006,1203732,8.5,tt0407887
10481,Mark Wahlberg,nm0000242,The Departed,2006,1203732,8.5,tt0407887
...,...,...,...,...,...,...,...
188620,Mark Stanley,nm4440305,Coriolanus,2014,1834,8.5,tt3313066
189881,Jasmine Cephas Jones,nm5093499,Hamilton,2020,61228,8.5,tt8503618
190513,Phillipa Soo,nm5623883,Hamilton,2020,61228,8.5,tt8503618
190684,Rochenda Sandall,nm5878360,Coriolanus,2014,1834,8.5,tt3313066
191219,Anthony Ramos,nm6588867,Hamilton,2020,61228,8.5,tt8503618

In [66]:
df.query("Votes > 1000000 and Rating >= 8")

,Actor,ActorID,Film,Year,Votes,Rating,FilmID
275,Marlon Brando,nm0000008,The Godfather,1972,1642278,9.2,tt0068646
1177,Alec Guinness,nm0000027,Star Wars: Episode V - The Empire Strikes Back,1980,1170934,8.7,tt0080684
1179,Alec Guinness,nm0000027,Star Wars: Episode IV - A New Hope,1977,1242945,8.6,tt0076759
3799,Brad Pitt,nm0000093,Inglourious Basterds,2009,1285359,8.3,tt0361748
3814,Brad Pitt,nm0000093,Fight Club,1999,1876882,8.8,tt0137523
...,...,...,...,...,...,...,...
188492,MacKenzie Meehan,nm4394776,The Wolf of Wall Street,2013,1209490,8.2,tt0993846
188503,Nicole Alexandra Shipley,nm4397494,Guardians of the Galaxy,2014,1055470,8.0,tt2015381
189015,Tyler Dean Flores,nm4561678,The Dark Knight Rises,2012,1533079,8.4,tt1345836
190036,Wyatt Oleff,nm5200476,Guardians of the Galaxy,2014,1055470,8.0,tt2015381
190233,Giselle Eisenberg,nm5338034,The Wolf of Wall Street,2013,1209490,8.2,tt0993846

### loc, iloc and other filtering techniques(except query) always return a view and changes made to them may effect the original DataFrame.
### So, always use .copy() function if you want to further manipulate your filtered data without your original data being manipulated.
### EX: df2 = df[["Actor","Film"]].copy()